version: '3.8'

services:
    web:
        build: ./todo_project
        restart: always
        entrypoint:
            - /usr/src/app/entrypoint-project.sh
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./todo_project/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./env.project

